### ISSUE TITLE
Cannot unrar unacs files on Ubuntu 16.10

### ISSUE THREAD

**Issue by blackyhn** [kodi1/service.subtitles.unacs#10]
15:19:51 T:2464361280  NOTICE: *** (u'"/home/tata/.kodi/userdata/addon_data/service.subtitles.unacs/temp/Stranger_Things_01_08.(subs.sab.bz).rar" -- "/home/tata/.kodi/userdata/addon_data/service.subtitles.unacs/temp/"',)
15:19:51 T:2923084224   ERROR: Extract, No archive given
15:19:51 T:2464361280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/tata/.kodi/addons/service.subtitles.unacs/service.py", line 236, in <module>
                                                subs = Download(params["ID"],params["link"],params["filename"])
                                              File "/home/tata/.kodi/addons/service.subtitles.unacs/service.py", line 151, in Download
                                                if xbmcvfs.exists(subtitle_list[0]):
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
15:19:51 T:2505005888   ERROR: GetDirectory - Error getting plugin://service.subtitles.unacs/?action=download&link=85315&ID=subs_sab&filename=filename of the subtitle

**Comment by blackyhn** [comment]
This is a quick and dirty fix. Change the XBMC.Extract with the rarfile lib class:

opened_rar = rarfile.RarFile(ff)
opened_rar.extractall(__temp__)

**Comment by kodi1** [comment]
#12
