### ISSUE TITLE
Проблем с почистването на кеш директорията

### ISSUE THREAD

**Issue by wizziLalev** [kodi1/service.subtitles.unacs#7]
Задравейте,
от известно време имам проблем с плъгина... На произволен принцип се появява проблем с почистването на кеш директорията (~/.kodi/user_data/addon_data/service.subtitles.unacs/temp) тогава се налага ръчно да изтрия всички файлове от нея и да и задам chmod 777, за да мога да използвам плъгина отново. Дали имате идея каква може да е причината за това поведение?
Поздрави!

**Comment by kodi1** [comment]
Log please http://kodi.wiki/view/Log_file/Easy
